// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xovhsekglutordhgsggs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvdmhzZWtnbHV0b3JkaGdzZ2dzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5Mjc5MjYsImV4cCI6MjA2MzUwMzkyNn0.FbGmq1XRlNS75K7NCYI5wq4HbrSnHGvnQpuPo4c-3fQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);